POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data" : [
        {
            "performanceId" : 1000000001,
            "festivalId" : 1100000001,
            "startTime" : "10:00",
            "endTime" : "11:00"
        },
         {
            "performanceId" : 1000000002,
            "festivalId" : 1100000001,
            "startTime" : "10:00",
            "endTime" : "11:00"
        },
         {
            "performanceId" : 1000000003,
            "festivalId" : 1100000001,
            "startTime" : "10:30",
            "endTime" : "11:30"
        },
         {
            "performanceId" : 1000000004,
            "festivalId" : 1100000002,
            "startTime" : "10:00",
            "endTime" : "11:00"
        },
         {
            "performanceId" : 1000000005,
            "festivalId" : 1100000002,
            "startTime" : "11:00",
            "endTime" : "12:00"
        },
         {
            "performanceId" : 1000000006,
            "festivalId" : 1100000002,
            "startTime" : "12:00",
            "endTime" : "13:00"
        },
         {
            "performanceId" : 1000000007,
            "festivalId" : 1100000002,
            "startTime" : "10:30",
            "endTime" : "12:30"
        },
         {
            "performanceId" : 1000000008,
            "festivalId" : 1100000003,
            "startTime" : "10:00",
            "endTime" : "11:00"
        },
          {
            "performanceId" : 1000000009,
            "festivalId" : 1100000003,
            "startTime" : "11:00",
            "endTime" : "12:00"
        },
         {
            "performanceId" : 1000000010,
            "festivalId" : 1100000003,
            "startTime" : "12:00",
            "endTime" : "13:00"
        },
         {
            "performanceId" : 1000000011,
            "festivalId" : 1100000003,
            "startTime" : "10:30",
            "endTime" : "12:30"
        },
         {
            "performanceId" : 1000000012,
            "festivalId" : 1100000003,
            "startTime" : "11:30",
            "endTime" : "11:30"
        },
         {
            "performanceId" : 1000000013,
            "festivalId" : 1100000004,
            "startTime" : "10:00",
            "endTime" : "11:00"
        },
         {
            "performanceId" : 1000000014,
            "festivalId" : 1100000004,
            "startTime" : "11:00",
            "endTime" : "12:00"
        },
         {
            "performanceId" : 1000000015,
            "festivalId" : 1100000004,
            "startTime" : "12:00",
            "endTime" : "13:00"
        },
         {
            "performanceId" : 1000000016,
            "festivalId" : 1100000004,
            "startTime" : "10:30",
            "endTime" : "12:30"
        },
         {
            "performanceId" : 1000000017,
            "festivalId" : 1100000004,
            "startTime" : "11:30",
            "endTime" : "13:30"
        },
         {
            "performanceId" : 1000000018,
            "festivalId" : 1100000004,
            "startTime" : "09:00",
            "endTime" : "12:00"
        }
    ]
}

###
GET https://saryl-test.herokuapp.com/basic/data?festivalId=1100000001&startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;

###
GET http://localhost:3000/basic/data?festivalId=1100000002&startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;



###
GET https://saryl-test.herokuapp.com/basic/data?startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;

###
GET http://localhost:3000/basic/data?startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;



###
GET https://saryl-test.herokuapp.com/basic/result?festivalId=1100000001 HTTP/1.1
Content-Type: application/json;

###
GET https://saryl-test.herokuapp.com/basic/result?festivalId=1100000002 HTTP/1.1
Content-Type: application/json;


###
GET http://localhost:3000/basic/result?festivalId=1100000002 HTTP/1.1
Content-Type: application/json;



###
POST http://localhost:3000/advance/insert HTTP/1.1
Content-Type: application/json

{
    "data": [
  {
    "performanceId": 1000000001,
    "startTime": "100000",
    "endTime": "110000",
    "festivalId": 1100000001,
    "popularity": 1
  },
  {
    "performanceId": 1000000002,
    "startTime": "100000",
    "endTime": "110000",
    "festivalId": 1100000001,
    "popularity": 1
  },
  {
    "performanceId": 1000000003,
    "startTime": "103000",
    "endTime": "113000",
    "festivalId": 1100000001,
    "popularity": 10
  },
  {
    "performanceId": 1000000004,
    "startTime": "100000",
    "endTime": "110000",
    "festivalId": 1100000002,
    "popularity": 1
  },
  {
    "performanceId": 1000000005,
    "startTime": "110000",
    "endTime": "120000",
    "festivalId": 1100000002,
    "popularity": 1
  },
  {
    "performanceId": 1000000006,
    "startTime": "120000",
    "endTime": "130000",
    "festivalId": 1100000002,
    "popularity": 1
  },
  {
    "performanceId": 1000000007,
    "startTime": "103000",
    "endTime": "123000",
    "festivalId": 1100000002,
    "popularity": 3
  },
  {
    "performanceId": 1000000008,
    "startTime": "100000",
    "endTime": "110000",
    "festivalId": 1100000003,
    "popularity": 1	
  },
  {
    "performanceId": 1000000009,
    "startTime": "110000",
    "endTime": "120000",
    "festivalId": 1100000003,
    "popularity": 1	
  },
  {
    "performanceId": 1000000010,
    "startTime": "120000",
    "endTime": "130000",
    "festivalId": 1100000003,
    "popularity": 1	
  },
  {
    "performanceId": 1000000011,
    "startTime": "103000",
    "endTime": "123000",
    "festivalId": 1100000003,
    "popularity": 1	
  },
  {
    "performanceId": 1000000012,
    "startTime": "113000",
    "endTime": "130000",
    "festivalId": 1100000003,
    "popularity": 3	
  },
  {
    "performanceId": 1000000013,
    "startTime": "100000",
    "endTime": "110000",
    "festivalId": 1100000004,
    "popularity": 1
  },
  {
    "performanceId": 1000000014,
    "startTime": "110000",
    "endTime": "120000",
    "festivalId": 1100000004,
    "popularity": 1
  },
  {
    "performanceId": 1000000015,
    "startTime": "120000",
    "endTime": "130000",
    "festivalId": 1100000004,
    "popularity": 2
  },
  {
    "performanceId": 1000000016,
    "startTime": "103000",
    "endTime": "123000",
    "festivalId": 1100000004,
    "popularity": 3
  },
  {
    "performanceId": 1000000017,
    "startTime": "113000",
    "endTime": "133000",
    "festivalId": 1100000004,
    "popularity": 4
  },
  {
    "performanceId": 1000000018,
    "startTime": "090000",
    "endTime": "120000",
    "festivalId": 1100000004,
    "popularity": 5
  }
]
}



###
GET https://saryl-test.herokuapp.com/advance/data?festivalId=1100000002 HTTP/1.1
Content-Type: application/json;

###
GET http://localhost:3000/advance/data?festivalId=1100000001 HTTP/1.1
Content-Type: application/json;



###
GET https://saryl-test.herokuapp.com/advance/data?startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;

###
GET http://localhost:3000/advance/data?startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;



###
GET https://saryl-test.herokuapp.com/advance/data?festivalId=1100000001&startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;

###
GET http://localhost:3000/advance/data?festivalId=1100000002&startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;




###
GET https://saryl-test.herokuapp.com/advance/result?festivalId=1100000002 HTTP/1.1
Content-Type: application/json;

###
GET http://localhost:3000/advance/result?festivalId=1100000001 HTTP/1.1
Content-Type: application/json;


###
GET https://saryl-test.herokuapp.com/basic/data?festivalId=1100000002&startTime__gt=1000&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json;



###
GET http://localhost:3000/reset HTTP/1.1
Content-Type: application/json;